export const aiFlags = {
  CHECK_BAD_MOVE: "Avoids ineffective moves",
  TRY_TO_FAINT: "Goes for KO's",
  CHECK_VIABILITY: "Exploits effects",
  FORCE_SETUP_FIRST_TURN: "Sets up on first turn",
  RISKY: "Takes risks",
  PREFER_STRONGEST_MOVE: "Favors KO's",
  PREFER_BATON_PASS: "Baton Pass strategy",
  DOUBLE_BATTLE: "Uses double battle tactics",
  HP_AWARE: "HP Levels change strategy",
  POWERFUL_STATUS: "Prioritizes field effects",
  NEGATE_UNAWARE: "Ignores special ability effects",
  WILL_SUICIDE: "Will self-destruct",
  PREFER_STATUS_MOVES: "Favors status moves",
  STALL: "Stalling tactics",
  SMART_SWITCHING: "Switches-out Pokémon",
  SMART_MON_CHOICES: "Selects Pokémon wisely",
  ACE_POKEMON: "Reserves strongest Pokémon",
  OMNISCIENT: "Sees your moves and items",
  CONSERVATIVE: "Assumes minimum damage",
  SEQUENCE_SWITCHING: "Uses Pokémon in fixed order",
  DOUBLE_ACE_POKEMON: "Saves strongest 2 Pokémon",
};
