import { config, UseSpringProps } from "react-spring";
import frames from "../data/newframes.json";

const animConfigs = (id: number): [number[][], any] => {
  const pkmn = frames.find((fd) => fd.dexID === id);
  console.log(pkmn);
  if (pkmn === undefined || pkmn.frames === undefined) {
    console.error("No animation for", id);
    return [[0, 0], () => {}];
  }
  const anim = pkmn.animation || "ANIM_H_VIBRATE";
  if (typeof anim !== "function") {
    return [pkmn.frames, configs["ANIM_H_VIBRATE"]];
  }
  return [pkmn.frames, configs[anim]];
};
const configs = {
  ANIM_V_SQUISH_AND_BOUNCE: (frame: number) => ({
    x: frame === 0 ? 0 : 5,
    scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_CIRCULAR_STRETCH_TWICE: (frame: number) => ({
    x: frame === 0 ? 0 : 5,
    scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_H_VIBRATE: (frame: number): UseSpringProps => ({
    // x: frame === 0 ? 0 : 5,
    scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_H_SLIDE: (frame: number) => ({
    x: frame === 0 ? 0 : 5,
    scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_V_SLIDE: (frame: number) => ({
    x: frame === 0 ? 0 : 5,
    scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_BOUNCE_ROTATE_TO_SIDES: (frame: number) => ({
    x: frame === 0 ? 0 : 2,
    rotate: frame === 0 ? 0 : 13,
    // scale: frame === 0 ? [1, 1] : [1, 1.05],
  }),
  ANIM_V_JUMPS_H_JUMPS: (frame: number): UseSpringProps => ({
    y: frame === 0 ? 0 : -10,
    config: {
      mass: 2,
    },
    // x: frame === 0 ? 0 : 50,
    // rotate: frame === 1 ? 10 : 0, // Rotate for state 1
    scale: frame === 0 ? [1, 1] : [1, 1.05],

    // matrix: frame === 0 ? [0, 0, 0, 0, 0, 0] : [0, 0, 0, 1, 0, 0],
  }),
};
// ANIM_ROTATE_TO_SIDES: {},
// ANIM_ROTATE_TO_SIDES_TWICE: {},
// ANIM_GROW_VIBRATE: {},
// ANIM_ZIGZAG_FAST: {},
// ANIM_SWING_CONCAVE: {},
// ANIM_SWING_CONCAVE_FAST: {},
// ANIM_SWING_CONVEX: {},
// ANIM_SWING_CONVEX_FAST: {},
// ANIM_H_SHAKE: {},
// ANIM_V_SHAKE: {},
// ANIM_CIRCULAR_VIBRATE: {},
// ANIM_TWIST: {},
// ANIM_SHRINK_GROW: {},
// ANIM_CIRCLE_C_CLOCKWISE: {},
// ANIM_GLOW_BLACK: {},
// ANIM_H_STRETCH: {},
// ANIM_V_STRETCH: {},
// ANIM_RISING_WOBBLE: {},
// ANIM_V_SHAKE_TWICE: {},
// ANIM_TIP_MOVE_FORWARD: {},
// ANIM_H_PIVOT: {},
// // ANIM_V_SLIDE_WOBBLE: { from: { x: -5, rotate: -5 }, to: { x: 0, rotate: 0 } },
// ANIM_H_SLIDE_WOBBLE: {},
// ANIM_V_JUMPS_BIG: {},
// ANIM_SPIN_LONG: {},
// ANIM_GLOW_ORANGE: {},
// ANIM_GLOW_RED: {},
// ANIM_GLOW_BLUE: {},
// ANIM_GLOW_YELLOW: {},
// ANIM_GLOW_PURPLE: {},
// ANIM_BACK_AND_LUNGE: {},
// ANIM_BACK_FLIP: {},
// ANIM_FLICKER: {},
// ANIM_BACK_FLIP_BIG: {},
// ANIM_FRONT_FLIP: {},
// ANIM_TUMBLING_FRONT_FLIP: {},
// ANIM_FIGURE_8: {},
// ANIM_FLASH_YELLOW: {},
// ANIM_SWING_CONCAVE_FAST_SHORT: {},
// ANIM_SWING_CONVEX_FAST_SHORT: {},
// ANIM_ROTATE_UP_SLAM_DOWN: {},
// ANIM_DEEP_V_SQUISH_AND_BOUNCE: {},
// ANIM_H_JUMPS: {},
// ANIM_H_JUMPS_V_STRETCH: {},
// ANIM_ROTATE_TO_SIDES_FAST: {},
// ANIM_ROTATE_UP_TO_SIDES: {},
// ANIM_FLICKER_INCREASING: {},
// ANIM_TIP_HOP_FORWARD: {},
// ANIM_PIVOT_SHAKE: {},
// ANIM_TIP_AND_SHAKE: {},
// ANIM_VIBRATE_TO_CORNERS: {},
// ANIM_GROW_IN_STAGES: {},
// ANIM_V_SPRING: {},
// ANIM_V_REPEATED_SPRING: {},
// ANIM_SPRING_RISING: {},
// ANIM_H_SPRING: {},
// ANIM_H_REPEATED_SPRING_SLOW: {},
// ANIM_H_SLIDE_SHRINK: {},
// ANIM_LUNGE_GROW: {},
// ANIM_CIRCLE_INTO_BG: {},
// ANIM_RAPID_H_HOPS: {},
// ANIM_FOUR_PETAL: {},
// ANIM_V_SQUISH_AND_BOUNCE_SLOW: {},
// ANIM_H_SLIDE_SLOW: {},
// ANIM_V_SLIDE_SLOW: {},
// ANIM_BOUNCE_ROTATE_TO_SIDES_SMALL: {},
// ANIM_BOUNCE_ROTATE_TO_SIDES_SLOW: {},
// ANIM_BOUNCE_ROTATE_TO_SIDES_SMALL_SLOW: {},
// ANIM_ZIGZAG_SLOW: {},
// ANIM_H_SHAKE_SLOW: {},
// ANIM_V_SHAKE_SLOW: {},
// ANIM_TWIST_TWICE: {},
// ANIM_CIRCLE_C_CLOCKWISE_SLOW: {},
// ANIM_V_SHAKE_TWICE_SLOW: {},
// ANIM_V_SLIDE_WOBBLE_SMALL: {},
// ANIM_V_JUMPS_SMALL: {},
// ANIM_SPIN: {},
// ANIM_TUMBLING_FRONT_FLIP_TWICE: {},
// ANIM_DEEP_V_SQUISH_AND_BOUNCE_TWICE: {},
// ANIM_H_JUMPS_V_STRETCH_TWICE: {},
// ANIM_V_SHAKE_BACK: {},
// ANIM_V_SHAKE_BACK_SLOW: {},
// ANIM_V_SHAKE_H_SLIDE_SLOW: {},
// ANIM_V_STRETCH_BOTH_ENDS_SLOW: {},
// ANIM_H_STRETCH_FAR_SLOW: {},
// ANIM_V_SHAKE_LOW_TWICE: {},
// ANIM_H_SHAKE_FAST: {},
// ANIM_H_SLIDE_FAST: {},
// ANIM_H_VIBRATE_FAST: {},
// ANIM_H_VIBRATE_FASTEST: {},
// ANIM_V_SHAKE_BACK_FAST: {},
// ANIM_V_SHAKE_LOW_TWICE_SLOW: {},
// ANIM_V_SHAKE_LOW_TWICE_FAST: {},
// ANIM_CIRCLE_C_CLOCKWISE_LONG: {},
// ANIM_GROW_STUTTER_SLOW: {},
// ANIM_V_SHAKE_H_SLIDE: {},
// ANIM_V_SHAKE_H_SLIDE_FAST: {},
// ANIM_TRIANGLE_DOWN_SLOW: {},
// ANIM_TRIANGLE_DOWN: {},
// ANIM_TRIANGLE_DOWN_TWICE: {},
// ANIM_GROW: {},
// ANIM_GROW_TWICE: {},
// ANIM_H_SPRING_FAST: {},
// ANIM_H_SPRING_SLOW: {},
// ANIM_H_REPEATED_SPRING_FAST: {},
// ANIM_H_REPEATED_SPRING: {},
// ANIM_SHRINK_GROW_FAST: {},
// ANIM_SHRINK_GROW_SLOW: {},
// ANIM_V_STRETCH_BOTH_ENDS: {},
// ANIM_V_STRETCH_BOTH_ENDS_TWICE: {},
// ANIM_H_STRETCH_FAR_TWICE: {},
// ANIM_H_STRETCH_FAR: {},
// ANIM_GROW_STUTTER_TWICE: {},
// ANIM_GROW_STUTTER: {},
// ANIM_CONCAVE_ARC_LARGE_SLOW: {},
// ANIM_CONCAVE_ARC_LARGE: {},
// ANIM_CONCAVE_ARC_LARGE_TWICE: {},
// ANIM_CONVEX_DOUBLE_ARC_SLOW: {},
// ANIM_CONVEX_DOUBLE_ARC: {},
// ANIM_CONVEX_DOUBLE_ARC_TWICE: {},
// ANIM_CONCAVE_ARC_SMALL_SLOW: {},
// ANIM_CONCAVE_ARC_SMALL: {},
// ANIM_CONCAVE_ARC_SMALL_TWICE: {},
// ANIM_H_DIP: {},
// ANIM_H_DIP_FAST: {},
// ANIM_H_DIP_TWICE: {},
// ANIM_SHRINK_GROW_VIBRATE_FAST: {},
// ANIM_SHRINK_GROW_VIBRATE: {},
// ANIM_SHRINK_GROW_VIBRATE_SLOW: {},
// ANIM_JOLT_RIGHT_FAST: {},
// ANIM_JOLT_RIGHT: {},
// ANIM_JOLT_RIGHT_SLOW: {},
// ANIM_SHAKE_FLASH_YELLOW_FAST: {},
// ANIM_SHAKE_FLASH_YELLOW: {},
// ANIM_SHAKE_FLASH_YELLOW_SLOW: {},
// ANIM_SHAKE_GLOW_RED_FAST: {},
// ANIM_SHAKE_GLOW_RED: {},
// ANIM_SHAKE_GLOW_RED_SLOW: {},
// ANIM_SHAKE_GLOW_GREEN_FAST: {},
// ANIM_SHAKE_GLOW_GREEN: {},
// ANIM_SHAKE_GLOW_GREEN_SLOW: {},
// ANIM_SHAKE_GLOW_BLUE_FAST: {},
// ANIM_SHAKE_GLOW_BLUE: {},
// ANIM_SHAKE_GLOW_BLUE_SLOW: {},
// ANIM_SHAKE_GLOW_BLACK_SLOW: {},
// ANIM_SHAKE_GLOW_WHITE_SLOW: {},
// ANIM_SHAKE_GLOW_PURPLE_SLOW: {},
// }
export default animConfigs;
export { animConfigs };
